### ISSUE TITLE
Stuck in the sky after applying settings

### ISSUE THREAD

**Issue by figuld** [RavinMaddHatter/BedrockSkyblock#1]
After clicking `Submit` and message in chat `You have been teleported to X Y Z`, I'm still stuck at the sky Y=319 and different (and changing over time) X and Z. I can only get out of it using creative mod and relogging to the world, then manually tp myself to the cords in the chat message.

I'm on Arch Linux, using [the special launcher](https://github.com/minecraft-linux/mcpelauncher-manifest) to launch the Android version.

Clicking `Respawn` causes the issue again.

Sometimes it works and places me on an island after the short time, but respawn is still broken.

**Comment by RavinMaddHatter** [comment]
This happens on Linux due to the file system sort. It is loads the fries in
the wrong order... I don't know how to fix it...

**Comment by figuld** [comment]
@RavinMaddHatter @bud-aj29, could you explain further? So, maybe I, or someone else, who will see this issue, could help? Is the issue connected to the json files or the js script?

**Comment by RavinMaddHatter** [comment]
You can turn on content log. I don't remember specifically what file it is,
but there is a file that sets the global coordinates as a variable. This is
used in every other file to determine if the chuck is in 0/0 to bring in an
island structure. If that variable can't be found all island generation
breaks, because it can't check if it is the 0/0 Chunk. The way the works in
Windows is that you load the file names in a specific order, so the
variable gets set previous to the other files starting.

**Comment by figuld** [comment]
Here's version sort in linux:
```
$ /usr/bin/ls -1 -v Skyblock-3-1/
LICENSE
Manifest.json
features
feature_rules
pack_icon.png
scripts
```
[People say it replicates Windows sort.](https://unix.stackexchange.com/questions/471442/windows-explorer-natural-order-sort-order/471443#471443) Can you confirm it? I don't have Windows installation around.

In case it does, here're the diffs (- linux, + windows):
```
$ for dir in ./ */ */*/; do echo "Dir $dir"; diff --unified <(/usr/bin/ls -1 "$dir") <(/usr/bin/ls -1 -v "$dir"); done
Dir ./
--- /dev/fd/63	2024-05-08 01:46:12.869334393 +0300
+++ /dev/fd/62	2024-05-08 01:46:12.875334527 +0300
@@ -1,6 +1,6 @@
-feature_rules
-features
 LICENSE
 Manifest.json
+features
+feature_rules
 pack_icon.png
 scripts
Dir feature_rules/
--- /dev/fd/63	2024-05-08 01:46:12.883334706 +0300
+++ /dev/fd/62	2024-05-08 01:46:12.879334617 +0300
@@ -1,3 +1,3 @@
 isl
-v_mute
 void
+v_mute
Dir features/
--- /dev/fd/63	2024-05-08 01:46:12.884334729 +0300
+++ /dev/fd/62	2024-05-08 01:46:12.885334751 +0300
@@ -10,8 +10,8 @@
 0_n_v_fs_gravel.json
 0_n_v_fs_lava.json
 0_n_v_fs_magma.json
-0_n_v_fs_nether_gold_ore.json
 0_n_v_fs_netherrack.json
+0_n_v_fs_nether_gold_ore.json
 0_n_v_fs_nether_wart_block.json
 0_n_v_fs_quartz_ore.json
 0_n_v_fs_red_mushroom.json
@@ -24,9 +24,9 @@
 0_o_v_fs_blue_ice.json
 0_o_v_fs_calcite.json
 0_o_v_fs_copper_ore.json
+0_o_v_fs_deepslate.json
 0_o_v_fs_deepslate_copper_ore.json
 0_o_v_fs_deepslate_iron_ore.json
-0_o_v_fs_deepslate.json
 0_o_v_fs_dirt.json
 0_o_v_fs_flowing_lava.json
 0_o_v_fs_flowing_water.json
@@ -62,8 +62,8 @@
 1_n_v_fb_gravel.json
 1_n_v_fb_lava.json
 1_n_v_fb_magma.json
-1_n_v_fb_nether_gold_ore.json
 1_n_v_fb_netherrack.json
+1_n_v_fb_nether_gold_ore.json
 1_n_v_fb_nether_wart_block.json
 1_n_v_fb_quartz_ore.json
 1_n_v_fb_red_mushroom.json
@@ -76,9 +76,9 @@
 1_o_v_fb_blue_ice.json
 1_o_v_fb_calcite.json
 1_o_v_fb_copper_ore.json
+1_o_v_fb_deepslate.json
 1_o_v_fb_deepslate_copper_ore.json
 1_o_v_fb_deepslate_iron_ore.json
-1_o_v_fb_deepslate.json
 1_o_v_fb_dirt.json
 1_o_v_fb_flowing_lava.json
 1_o_v_fb_flowing_water.json
@@ -540,8 +540,8 @@
 v_orange_terracotta_replace.json
 v_orchid.json
 v_podzol_replace.json
-v_pool_grass.json
 v_pool.json
+v_pool_grass.json
 v_powder_snow_replace.json
 v_pumpkin.json
 v_red_mushroom.json
@@ -554,9 +554,9 @@
 v_reeds.json
 v_root_snap.json
 v_sand.json
-v_sand_replace.json
 v_sandstone.json
 v_sandstone_replace.json
+v_sand_replace.json
 v_seagrass.json
 v_sea_pickle.json
 v_snow_layer.json
@@ -570,8 +570,8 @@
 v_twisting_vines.json
 v_warped_nylium_replace.json
 v_warped_tree.json
-v_water_connect_replace.json
 v_waterlily.json
+v_water_connect_replace.json
 v_water_replace.json
 v_white_terracotta_replace.json
 v_yellow_flower.json
Dir scripts/
Dir feature_rules/isl/
Dir feature_rules/v_mute/
--- /dev/fd/63	2024-05-08 01:46:12.902335133 +0300
+++ /dev/fd/62	2024-05-08 01:46:12.903335155 +0300
@@ -79,10 +79,10 @@
 mountains_underground_coal_ore_feature.json
 mushroom_island_surface_huge_mushroom_feature.json
 mushroom_island_surface_mushrooms_feature.json
+netherwart_forest_trees_feature.json
 nether_cave_carver_feature.json
 nether_soul_sand_underground_feature_rules.json
 nether_sprouts_feature_rules.json
-netherwart_forest_trees_feature.json
 ocean_surface_kelp_feature.json
 ocean_surface_seagrass_feature.json
 overworld_amethyst_geode_feature.json
Dir feature_rules/void/
--- /dev/fd/63	2024-05-08 01:46:12.912335357 +0300
+++ /dev/fd/62	2024-05-08 01:46:12.908335267 +0300
@@ -10,8 +10,8 @@
 1_n_v_fr_gravel.json
 1_n_v_fr_lava.json
 1_n_v_fr_magma.json
-1_n_v_fr_nether_gold_ore.json
 1_n_v_fr_netherrack.json
+1_n_v_fr_nether_gold_ore.json
 1_n_v_fr_nether_wart_block.json
 1_n_v_fr_quartz_ore.json
 1_n_v_fr_red_mushroom.json
@@ -24,9 +24,9 @@
 1_o_v_fr_blue_ice.json
 1_o_v_fr_calcite.json
 1_o_v_fr_copper_ore.json
+1_o_v_fr_deepslate.json
 1_o_v_fr_deepslate_copper_ore.json
 1_o_v_fr_deepslate_iron_ore.json
-1_o_v_fr_deepslate.json
 1_o_v_fr_dirt.json
 1_o_v_fr_flowing_lava.json
 1_o_v_fr_flowing_water.json
```
`Manifest.json` is special and always loads first, right?
Are folder names hardcoded and you can't rename them?

**Comment by RavinMaddHatter** [comment]
The files named with 0 first need to load before the ones with 1 first....
And that isn't happening in Linux for some reason... It should..  but it
doesn't

**Comment by RavinMaddHatter** [comment]
Folders are hard coded

**Comment by figuld** [comment]
> The files named with 0 first need to load before the ones with 1 first

In `features/` folder the order seems right. The only way this can happen is that `feature_rules/void/` folder loads before the `features/`.

> You can turn on content log.

It doesn't really show anything:
```
14:58:47[Scripting][inform]-Plugin [Skyblock 3.1] - promoted [@minecraft/server] from [1.5.0] to [1.10.0] requested by [Skyblock 3.1 - 1.0.0].

14:58:47[Scripting][inform]-Plugin [Skyblock 3.1] - promoted [@minecraft/server] from [1.2.0] to [1.10.0] requested by [@minecraft/server-ui - 1.1.0].

14:58:57[Structure][error]-[[Jigsaw Structure]] couldn't be constructed, no pool named `minecraft:trial_chambers/chamber/end`

14:59:20[Scripting][warning]-[Watchdog] 188.968 ms script spike detected in behavior pack 'Skyblock 3.1'

15:01:19[Texture][warning]-Failed to find either texture set or image file of name (assets/images)
```
And then these messages repeat in random order.

But what if the issue doesn't have to anything with the ordering at all? I noticed that the game doesn't see the pack at all if I import it (It says `Import started...`, but no success or fails message like with other packs) or manually unzip to the `behaviour_packs/`. It works only if I put the mcpack file directly into the folder, and even then there's missing icon on the creation world screen (but not in storage settings menu).

P.S. So I renamed `Manifest.json` to `manifest.json` in the mcpack file like in other packs, imported it, the game saw it and the pack icon in world creation is not missing. (And renaming it inside already unpacked files works as well.)

But it didn't seemed to fix the issue... (Maybe it works randomly and puts me on an island more often?)
I created a new world, it put me on an island. Created again, stuck at the sky, rejoined the world, died, respawned, it put me on an island, died again, another island, died 3rd time, stuck at the sky...
Another world, stuck at the sky, (died) then put on an island, then stuck again...

If it's the file issue, should it not work at all? Maybe it's the weak hardware issue and the chunks aren't loading fast enough?
Maybe I should have mentioned it, I have a potato cpu laptop:
```
$ lscpu
Architecture:             x86_64
  CPU op-mode(s):         32-bit, 64-bit
  Address sizes:          39 bits physical, 48 bits virtual
  Byte Order:             Little Endian
CPU(s):                   4
  On-line CPU(s) list:    0-3
Vendor ID:                GenuineIntel
  Model name:             Intel(R) Celeron(R) N5100 @ 1.10GHz
    CPU family:           6
    Model:                156
    Thread(s) per core:   1
    Core(s) per socket:   4
    Socket(s):            1
    Stepping:             0
    CPU(s) scaling MHz:   100%
    CPU max MHz:          2800.0000
    CPU min MHz:          800.0000
    BogoMIPS:             2227.20
    Flags:                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts
                           acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc art arch_per
                          fmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq p
                          ni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg cx16 xtpr pdcm sse4_1 sse
                          4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave rdrand lahf_lm 3dnowprefetch c
                          puid_fault epb cat_l2 cdp_l2 ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow flexprio
                          rity ept vpid ept_ad fsgsbase tsc_adjust smep erms rdt_a rdseed smap clflushopt clw
                          b intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves split_lock_detect dtherm ida arat 
                          pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req vnmi umip waitpkg gfni rd
                          pid movdiri movdir64b md_clear flush_l1d arch_capabilities
Virtualization features:  
  Virtualization:         VT-x
Caches (sum of all):      
  L1d:                    128 KiB (4 instances)
  L1i:                    128 KiB (4 instances)
  L2:                     1.5 MiB (1 instance)
  L3:                     4 MiB (1 instance)
NUMA:                     
  NUMA node(s):           1
  NUMA node0 CPU(s):      0-3
```
It does handle Minecraft ok (with max on Android version 12 chunks render distance and 8 chunks simulation distance), though sometimes chunks aren't loading fast enough when I explore a world with an elytra.

Do you have a potato pc (with widows) around to check if that's the case (or powerful pc with linux and renamed `manifest.json` to see if issue is still happening)?

**Comment by RavinMaddHatter** [comment]
You will never get the lag down until they change world gen stuff.

**Comment by figuld** [comment]
So, during being stuck in the sky, I decided to wait, and after 10-13 minutes (it's random, previous time it was 2 minutes) I finally got tped to an island. So, file sort isn't the issue here?

I think renaming `Manifest.json` -> `manifest.json` (for all your packs, so that they import successfully) and making a new release should be enough for now.

**Comment by RavinMaddHatter** [comment]
Interesting
